version: "3.9"

services:
  # backend:
  #   build: ./backend
  #   container_name: insightflow-backend
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - "8000:8000"
  #   restart: always

  frontend:
    build: ./frontend
    container_name: insightflow-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
